## Creating arrays from txt data
#### MNE can't use txt data, so will have to convert into 3D arrays
#### [Tutorial](https://mne.tools/stable/auto_tutorials/simulation/10_array_objs.html)

In [2]:
import numpy as np 
import mne

In [ ]:
data = np.loadtxt('data/focus_test.txt', delimiter=',', skiprows=5, usecols=(0,1,2,3,4), max_rows=5) #5 rows for testing, MNE requires arrays in form of (n_channels, n_samples)
print(data)
print(data.ndim) #should be 2 for MNE
#need to use the overall structure to prepackage the data in the right way
#might want to use BIDS format for built in pipeline

[[   0.         -128.08970353  -66.78713341  -63.57829925  -71.96689485]
 [   1.         -128.16076163  -53.72366286  -46.06808765  -48.21105033]
 [   1.         -130.06811061  -60.26848779  -42.90787219  -57.50096182]
 [   2.         -132.31579048  -69.58831848  -32.15939972  -51.07955359]
 [   2.         -128.93118102  -59.2774143   -26.50841089  -41.9953366 ]]
2
